package GUI;/*

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import ServiceLayer.LoginServ;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;

/**
 *
 * @author homeguard
 */
public class EventWindow extends javax.swing.JFrame {
    private LoginServ loginServ;
    private int eventID;
    /**
     * Creates new form training
     */
    private void backButtonActionPerformed(ActionEvent e) {
        this.dispose();
        MenuWindow menuWindow = new MenuWindow(loginServ);
        menuWindow.start();
    }

    private void editButtonActionPerformed(ActionEvent e) {
        int selectedRow = table1.getSelectedRow();
        if (selectedRow < 0) {
            ModalDialog.showEror(this, "Select event");
            return;
        }
        String eventType = (String)table1.getValueAt(selectedRow, 2);
        eventID = (Integer)table1.getValueAt(selectedRow, 0);
        this.dispose();
        if (eventType.equals("Game")) {
            EditGameWindow editGame = new EditGameWindow(loginServ, eventID);
            editGame.start();
        }else {
           EditTrainingWindow editTrainingWindow = new EditTrainingWindow(loginServ, eventID);
            editTrainingWindow.start();
        }
    }

    private void heloButtonActionPerformed(ActionEvent e) {
        this.dispose();
        HelperWindow helperWindow = new HelperWindow(loginServ);
        helperWindow.start();
    }

    private void deleteButtonActionPerformed(ActionEvent e) {
        int selectedRow = table1.getSelectedRow();
        if (selectedRow < 0) {
            ModalDialog.showEror(this, "Select event");
            return;
        }
        String eventType = (String)table1.getValueAt(selectedRow, 2);
        eventID = (Integer)table1.getValueAt(selectedRow, 0);
        if (eventType.equals("Game")) {
           loginServ.deleteGame(eventID);
        }else {
            loginServ.deleteTrain(eventID);
        }
        ModalDialog.showComplete(this, "Deleted");
        this.dispose();
        start();
    }

    public EventWindow(LoginServ loginServ) {
        this.loginServ = loginServ;
        initComponents();
        if (!loginServ.isAdmin()) {
            deleteButton.setEnabled(false);
            editButton.setEnabled(false);
            heloButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  //  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Anton Vsegda
    private void initComponents() {
        jScrollPane1 = new JScrollPane();
        table1 = new JTable();
        label1 = new JLabel();
        deleteButton = new JButton();
        editButton = new JButton();
        heloButton = new JButton();
        backButton = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        Container contentPane = getContentPane();

        //======== jScrollPane1 ========
        {

            //---- table1 ----
            table1.setModel(new DefaultTableModel(
                loginServ.getEvents(),
                new String[] {
                    "ID", "\u0414\u0430\u0442\u0430", "\u0422\u0438\u043f", "\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f"
                }
            ) {
                Class<?>[] columnTypes = new Class<?>[] {
                    Integer.class, Date.class, String.class, String.class
                };
                boolean[] columnEditable = new boolean[] {
                    false, false, false, false
                };
                @Override
                public Class<?> getColumnClass(int columnIndex) {
                    return columnTypes[columnIndex];
                }
                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return columnEditable[columnIndex];
                }
            });
            jScrollPane1.setViewportView(table1);
        }

        //---- label1 ----
        label1.setText("\u0413\u0440\u0430\u0444\u0438\u043a \u043c\u0435\u0440\u043e\u043f\u0440\u0438\u044f\u0442\u0438\u0439 \u043a\u043e\u043c\u0430\u043d\u0434\u044b \u043d\u0430 2 \u043d\u0435\u0434\u0435\u043b\u0438");

        //---- deleteButton ----
        deleteButton.setText("\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0441\u043e\u0431\u044b\u0442\u0438\u0435");
        deleteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                deleteButtonActionPerformed(e);
            }
        });

        //---- editButton ----
        editButton.setText("\u0418\u0437\u043c\u0435\u043d\u0438\u0442\u044c \u0441\u043e\u0431\u044b\u0442\u0438\u0435");
        editButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                editButtonActionPerformed(e);
            }
        });

        //---- heloButton ----
        heloButton.setText("\u041f\u043e\u043c\u043e\u0448\u043d\u0438\u043a");
        heloButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                heloButtonActionPerformed(e);
            }
        });

        //---- backButton ----
        backButton.setText("\u043d\u0430\u0437\u0430\u0434");
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                backButtonActionPerformed(e);
            }
        });

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(deleteButton)
                    .addGap(80, 80, 80)
                    .addComponent(editButton)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                    .addComponent(heloButton, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
                    .addGap(64, 64, 64))
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(backButton)
                            .addGap(138, 138, 138)
                            .addComponent(label1))
                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 592, GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(34, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                        .addComponent(label1)
                        .addComponent(backButton))
                    .addGap(37, 37, 37)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 226, GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(deleteButton)
                        .addComponent(editButton)
                        .addComponent(heloButton))
                    .addContainerGap(44, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    public void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventWindow(loginServ).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Anton Vsegda
    private JScrollPane jScrollPane1;
    private JTable table1;
    private JLabel label1;
    private JButton deleteButton;
    private JButton editButton;
    private JButton heloButton;
    private JButton backButton;
    // End of variables declaration//GEN-END:variables
}
